# Generated by Django 6.1.1 on 2026-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
