# Generated by Django 6.1.1 on 2026-10-02 11:26

from django.db import migrations

# Copied here on purpose: migrations must not depend on app code that may change.
STARTER_TAGS = ['python', 'django', 'testing', 'sql', 'javascript', 'devops']


def seed_starter_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    for name in STARTER_TAGS:
        Tag.objects.update_or_create(name=name, defaults={'starter': True})


def unseed_starter_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    Tag.objects.filter(name__in=STARTER_TAGS).update(starter=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_starter'),
    ]

    operations = [
        migrations.RunPython(seed_starter_tags, unseed_starter_tags),
    ]
