# Generated by Django 6.1.1 on 2026-10-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_seed_starter_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
