# Generated by Django 6.1.1 on 2026-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tags.tag'),
        ),
    ]
